"""GroundedChart: execution-grounded verification for language-to-chart generation."""

from grounded_chart.canonical_executor import CanonicalExecutor
from grounded_chart.backend import (
    BackendProfile,
    MATPLOTLIB_2D_PROFILE,
    MATPLOTLIB_3D_PROFILE,
    PLOTLY_PROFILE,
    UNKNOWN_BACKEND_PROFILE,
    infer_backend_name,
    infer_backend_profile,
)
from grounded_chart.config import AblationRunConfig, load_ablation_run_config, load_ablation_run_config_from_env
from grounded_chart.diagnostics import FailureAtom, failure_atoms_from_evidence_graph, failure_atoms_to_dicts
from grounded_chart.expected_artifacts import (
    ExpectedArtifactNode,
    ExpectedTraceExtraction,
    ExplicitPointExpectedTraceExtractor,
    LLMExpectedArtifactExtractor,
    StructuredExpectedArtifacts,
    compile_expected_artifacts_to_figure,
    extract_expected_trace_from_text,
    extract_expected_trace_from_texts,
)
from grounded_chart.evidence import (
    attach_figure_requirements,
    bind_requirement_policy_to_verification,
    build_evidence_graph,
    build_requirement_plan,
    derive_expected_figure,
    infer_requirement_id,
    merge_expected_figure_specs,
)
from grounded_chart.intent_parser import HeuristicIntentParser, IntentParser, LLMIntentParser
from grounded_chart.llm import (
    LLMClient,
    LLMCompletionTrace,
    LLMJsonResult,
    LLMUsage,
    OpenAICompatibleConfig,
    OpenAICompatibleLLMClient,
    extract_json_object,
)
from grounded_chart.patch_ops import PatchAnchor, PatchApplyResult, PatchOperation, apply_patch_operations, parse_patch_operations
from grounded_chart.pipeline import GroundedChartPipeline
from grounded_chart.plan_feedback import (
    normalize_figure_plan_feedback,
    normalize_layout_plan_feedback,
    normalize_plan_feedback_items,
    plan_updates_from_feedback,
)
from grounded_chart.repairer import LLMRepairer, Repairer, RuleBasedRepairer, TieredRepairer
from grounded_chart.repair_policy import (
    RepairActionClass,
    RepairGateDecision,
    RepairPlan,
    RuleBasedRepairPlanner,
    apply_auto_repair_gate,
    normalize_repair_policy_mode,
    repair_action_class_for_plan,
    repair_action_class_for_scope,
)
from grounded_chart.requirements import (
    Artifact,
    ChartRequirementPlan,
    EvidenceGraph,
    EvidenceLink,
    PanelRequirementPlan,
    RequirementNode,
)
from grounded_chart.schema import (
    ArtistTrace,
    AxisRequirementSpec,
    AxisTrace,
    ChartIntentPlan,
    DataPoint,
    FigureRequirementSpec,
    FigureTrace,
    FilterSpec,
    MeasureSpec,
    ParsedRequirementBundle,
    PipelineResult,
    PlotTrace,
    RepairAttempt,
    RepairPatch,
    SortSpec,
    TableSchema,
    VerificationError,
    VerificationReport,
)
from grounded_chart.code_structure import CodeStructureArtifact, extract_code_structure_artifacts
from grounded_chart.trace_runner import ManualTraceRunner, MatplotlibTraceRunner
from grounded_chart.verifier import OperatorLevelVerifier
from grounded_chart.visual_artifacts import (
    ActualVisualArtifact,
    ExpectedVisualArtifact,
    compile_expected_visual_artifacts,
    extract_actual_visual_artifacts,
    verify_expected_visual_artifacts,
)
from grounded_chart.codegen import (
    ChartCodeGeneration,
    ChartCodeGenerationRequest,
    ChartCodeGenerator,
    LLMChartCodeGenerator,
    StaticChartCodeGenerator,
)
from grounded_chart.rendering import ChartImageRenderer, ChartRenderResult
from grounded_chart.generation_pipeline import ChartGenerationPipeline, ChartGenerationPipelineResult
from grounded_chart.figure_reader import (
    FigureAudit,
    FigureReaderAgent,
    VLMFigureReaderAgent,
    figure_audit_plan_feedback,
    normalized_figure_audit_notes,
    write_figure_audit_artifact,
)
from grounded_chart.layout_critic import LayoutCriticAgent, LayoutCritique, LLMLayoutCriticAgent, VLMLayoutAgent
from grounded_chart.plan_agent import ChartPlanAgent, HeuristicPlanAgent, LLMPlanAgent, PlanAgentRequest, PlanAgentResult
from grounded_chart.plan_revision import LayoutOnlyPlanRevisionAgent, PlanRevisionAgent, PlanRevisionResult
from grounded_chart.executor_agent import (
    ExecutorFidelityIssue,
    ExecutorFidelityReport,
    ExecutorFidelityValidator,
    validate_executor_fidelity,
)
from grounded_chart.construction_plan import (
    ChartConstructionPlan,
    HeuristicChartConstructionPlanner,
    PlanDecision,
    PlanValidationIssue,
    PlanValidationReport,
    PlanValidator,
    VisualLayerPlan,
    VisualPanelPlan,
    validate_construction_plan,
)
from grounded_chart.source_data import SourceDataExecution, SourceDataExecutor, SourceDataPlan, SourceDataPlanner, SourceFileSummary

__all__ = [
    "Artifact",
    "ArtistTrace",
    "AxisRequirementSpec",
    "AxisTrace",
    "AblationRunConfig",
    "BackendProfile",
    "attach_figure_requirements",
    "bind_requirement_policy_to_verification",
    "build_evidence_graph",
    "build_requirement_plan",
    "CanonicalExecutor",
    "ChartCodeGeneration",
    "ChartCodeGenerationRequest",
    "ChartCodeGenerator",
    "ChartGenerationPipeline",
    "ChartGenerationPipelineResult",
    "ChartImageRenderer",
    "ChartIntentPlan",
    "ChartConstructionPlan",
    "ChartRenderResult",
    "ChartRequirementPlan",
    "ChartPlanAgent",
    "LayoutCriticAgent",
    "LayoutCritique",
    "LayoutOnlyPlanRevisionAgent",
    "CodeStructureArtifact",
    "DataPoint",
    "EvidenceGraph",
    "ExecutorFidelityIssue",
    "ExecutorFidelityReport",
    "ExecutorFidelityValidator",
    "compile_expected_artifacts_to_figure",
    "extract_expected_trace_from_texts",
    "extract_expected_trace_from_text",
    "ExplicitPointExpectedTraceExtractor",
    "ExpectedTraceExtraction",
    "StructuredExpectedArtifacts",
    "LLMExpectedArtifactExtractor",
    "ExpectedArtifactNode",
    "EvidenceLink",
    "FailureAtom",
    "FilterSpec",
    "FigureRequirementSpec",
    "FigureAudit",
    "FigureReaderAgent",
    "FigureTrace",
    "GroundedChartPipeline",
    "HeuristicIntentParser",
    "HeuristicChartConstructionPlanner",
    "HeuristicPlanAgent",
    "derive_expected_figure",
    "infer_backend_name",
    "infer_backend_profile",
    "infer_requirement_id",
    "IntentParser",
    "LLMClient",
    "LLMChartCodeGenerator",
    "LLMCompletionTrace",
    "LLMLayoutCriticAgent",
    "LLMPlanAgent",
    "VLMLayoutAgent",
    "VLMFigureReaderAgent",
    "LLMIntentParser",
    "LLMJsonResult",
    "LLMRepairer",
    "LLMUsage",
    "load_ablation_run_config",
    "load_ablation_run_config_from_env",
    "MATPLOTLIB_2D_PROFILE",
    "MATPLOTLIB_3D_PROFILE",
    "ManualTraceRunner",
    "MatplotlibTraceRunner",
    "MeasureSpec",
    "merge_expected_figure_specs",
    "OpenAICompatibleConfig",
    "OpenAICompatibleLLMClient",
    "OperatorLevelVerifier",
    "PatchAnchor",
    "PatchApplyResult",
    "PatchOperation",
    "PanelRequirementPlan",
    "ParsedRequirementBundle",
    "PipelineResult",
    "PlanDecision",
    "PlanAgentRequest",
    "PlanAgentResult",
    "PlanRevisionAgent",
    "PlanRevisionResult",
    "PlanValidationIssue",
    "PlanValidationReport",
    "PlanValidator",
    "PlotTrace",
    "PLOTLY_PROFILE",
    "RepairAttempt",
    "RepairActionClass",
    "RepairGateDecision",
    "RepairPatch",
    "RepairPlan",
    "Repairer",
    "RequirementNode",
    "RuleBasedRepairer",
    "RuleBasedRepairPlanner",
    "SortSpec",
    "SourceDataExecution",
    "SourceDataExecutor",
    "SourceDataPlan",
    "SourceDataPlanner",
    "SourceFileSummary",
    "StaticChartCodeGenerator",
    "TableSchema",
    "TieredRepairer",
    "UNKNOWN_BACKEND_PROFILE",
    "VerificationError",
    "VerificationReport",
    "validate_executor_fidelity",
    "validate_construction_plan",
    "VisualLayerPlan",
    "VisualPanelPlan",
    "verify_expected_visual_artifacts",
    "extract_actual_visual_artifacts",
    "extract_code_structure_artifacts",
    "compile_expected_visual_artifacts",
    "ExpectedVisualArtifact",
    "ActualVisualArtifact",
    "apply_auto_repair_gate",
    "apply_patch_operations",
    "extract_json_object",
    "failure_atoms_from_evidence_graph",
    "failure_atoms_to_dicts",
    "figure_audit_plan_feedback",
    "normalize_repair_policy_mode",
    "normalized_figure_audit_notes",
    "normalize_figure_plan_feedback",
    "normalize_layout_plan_feedback",
    "normalize_plan_feedback_items",
    "parse_patch_operations",
    "plan_updates_from_feedback",
    "repair_action_class_for_plan",
    "repair_action_class_for_scope",
    "write_figure_audit_artifact",
]
