"""GroundedChart: execution-grounded verification for language-to-chart generation."""

from grounded_chart.canonical_executor import CanonicalExecutor
from grounded_chart.backend import (
    BackendProfile,
    MATPLOTLIB_2D_PROFILE,
    MATPLOTLIB_3D_PROFILE,
    PLOTLY_PROFILE,
    UNKNOWN_BACKEND_PROFILE,
    infer_backend_name,
    infer_backend_profile,
)
from grounded_chart.config import AblationRunConfig, load_ablation_run_config, load_ablation_run_config_from_env
from grounded_chart.evidence import (
    attach_figure_requirements,
    build_evidence_graph,
    build_requirement_plan,
    derive_expected_figure,
    infer_requirement_id,
    merge_expected_figure_specs,
)
from grounded_chart.intent_parser import HeuristicIntentParser, IntentParser, LLMIntentParser
from grounded_chart.llm import LLMClient, OpenAICompatibleConfig, OpenAICompatibleLLMClient, extract_json_object
from grounded_chart.pipeline import GroundedChartPipeline
from grounded_chart.repairer import LLMRepairer, Repairer, RuleBasedRepairer, TieredRepairer
from grounded_chart.repair_policy import RepairPlan, RuleBasedRepairPlanner
from grounded_chart.requirements import (
    Artifact,
    ChartRequirementPlan,
    EvidenceGraph,
    EvidenceLink,
    PanelRequirementPlan,
    RequirementNode,
)
from grounded_chart.schema import (
    ArtistTrace,
    AxisRequirementSpec,
    AxisTrace,
    ChartIntentPlan,
    DataPoint,
    FigureRequirementSpec,
    FigureTrace,
    FilterSpec,
    MeasureSpec,
    ParsedRequirementBundle,
    PipelineResult,
    PlotTrace,
    RepairAttempt,
    RepairPatch,
    SortSpec,
    TableSchema,
    VerificationError,
    VerificationReport,
)
from grounded_chart.trace_runner import ManualTraceRunner, MatplotlibTraceRunner
from grounded_chart.verifier import OperatorLevelVerifier

__all__ = [
    "Artifact",
    "ArtistTrace",
    "AxisRequirementSpec",
    "AxisTrace",
    "AblationRunConfig",
    "BackendProfile",
    "attach_figure_requirements",
    "build_evidence_graph",
    "build_requirement_plan",
    "CanonicalExecutor",
    "ChartIntentPlan",
    "ChartRequirementPlan",
    "DataPoint",
    "EvidenceGraph",
    "EvidenceLink",
    "FilterSpec",
    "FigureRequirementSpec",
    "FigureTrace",
    "GroundedChartPipeline",
    "HeuristicIntentParser",
    "derive_expected_figure",
    "infer_backend_name",
    "infer_backend_profile",
    "infer_requirement_id",
    "IntentParser",
    "LLMClient",
    "LLMIntentParser",
    "LLMRepairer",
    "load_ablation_run_config",
    "load_ablation_run_config_from_env",
    "MATPLOTLIB_2D_PROFILE",
    "MATPLOTLIB_3D_PROFILE",
    "ManualTraceRunner",
    "MatplotlibTraceRunner",
    "MeasureSpec",
    "merge_expected_figure_specs",
    "OpenAICompatibleConfig",
    "OpenAICompatibleLLMClient",
    "OperatorLevelVerifier",
    "PanelRequirementPlan",
    "ParsedRequirementBundle",
    "PipelineResult",
    "PlotTrace",
    "PLOTLY_PROFILE",
    "RepairAttempt",
    "RepairPatch",
    "RepairPlan",
    "Repairer",
    "RequirementNode",
    "RuleBasedRepairer",
    "RuleBasedRepairPlanner",
    "SortSpec",
    "TableSchema",
    "TieredRepairer",
    "UNKNOWN_BACKEND_PROFILE",
    "VerificationError",
    "VerificationReport",
    "extract_json_object",
]
